### ISSUE TITLE
docker 1.13 legacy plugin: plugin not found

### ISSUE THREAD

**Issue by rolele** [omallo/docker-volume-plugin-dostorage#10]
Hi omallo,
great work, thank you very much for this plugin.
I am trying it for the first time but I had the bad luck to install the last version of docker 1.13 and it seems that they refactor the way plugins work.

here is the error I get while trying to create the volume;
```
docker volume create --driver dostorage --name myvol-01
Error response from daemon: create myvol-01: Error looking up volume plugin dostorage: legacy plugin: plugin not found
```

```
[root@managers ~]# docker version
Client:
 Version:      1.13.0
 API version:  1.25
 Go version:   go1.7.3
 Git commit:   49bf474
 Built:        Tue Jan 17 09:55:28 2017
 OS/Arch:      linux/amd64

Server:
 Version:      1.13.0
 API version:  1.25 (minimum version 1.12)
 Go version:   go1.7.3
 Git commit:   49bf474
 Built:        Tue Jan 17 09:55:28 2017
 OS/Arch:      linux/amd64
 Experimental: false
```

Cheers

**Comment by rolele** [comment]
Sorry to bother I did not start the plugin in the background using 
```
sudo docker-volume-plugin-dostorage --access-token=<your-API-Access-Token> &
```
now it worked well. Thanks

**Comment by omallo** [comment]
Hi @rolele , no problem at all. And BTW, I had also created an issue #9 to support the new plugin API finalised with Docker 1.13. I haven't looked at it in detail yet but, as you say, the old style of plugins should still be working.
